### ISSUE TITLE
Nota Informativa

### ISSUE THREAD

**Issue by PedroBallesteros11** [SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-1#1]
[Nota Informativa.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-1/files/10180417/Nota.Informativa.pdf)

**Comment by josealfredo79** [comment]
La nota informativa debe estar mejor estructurada

**Comment by josealfredo79** [comment]
Revisado
